### ISSUE TITLE
Unable to open any REL file (java.lang.NullPointerException)

### ISSUE THREAD

**Issue by Zen64** [Cuyler36/Ghidra-GameCube-Loader#31]
Been playing with Twilight Princess files and have encountered a weird error. I managed to disassemble AppLoader.ldr and Start.dol perfectly fine, but nothing else works.
I'm using Ghidra 9.1, I have the Gekko language files, I made sure that JDK was in path and JAVA_HOME, etc, everything seems fine, so I'm not sure what's causing this. (I've also tried reinstalling JDK and running Ghidra as admin.)

This occurs when opening any REL file, whether it's Yaz0 encoded, or decrypted with Yaz0dec, and happens whether or not I open its respective .map file.

---------------------------------------------------
Error importing file: decomp_d_a_title.rel
java.lang.NullPointerException
	at ghidra.app.util.MemoryBlockUtils.createUninitializedBlock(MemoryBlockUtils.java:69)
	at gamecubeloader.common.SystemMemorySections.Create(SystemMemorySections.java:11)
	at gamecubeloader.rel.RELProgramBuilder.<init>(RELProgramBuilder.java:127)
	at gamecubeloader.GameCubeLoader.loadProgramInto(GameCubeLoader.java:180)
	at ghidra.app.util.opinion.AbstractProgramLoader.loadInto(AbstractProgramLoader.java:169)
	at gamecubeloader.GameCubeLoader.loadProgram(GameCubeLoader.java:140)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:401)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:351)
	at ghidra.util.task.TaskLauncher$1.run(TaskLauncher.java:90)
	at ghidra.util.task.Task.monitoredRun(Task.java:126)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$1(TaskRunner.java:94)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

---------------------------------------------------
Build Date: 2019-Oct-23 1737 EDT
Ghidra Version: 9.1
Java Home: C:\Program Files\Amazon Corretto\jdk11.0.6_10
JVM Version: Amazon.com Inc. 11.0.6
OS: Windows 10 10.0 amd64
Workstation: DESKTOP-3HEF998
`

**Comment by Cuyler36** [comment]
Would this happen to be the Wii version? This loader is explicitly for GameCube titles. Wii games are not officially supported and only work due to how similar the architecture is.

That being said, you can get around this problem by unchecking the "Create OS global memory section & hardware register memory sections" option in the loader options when initially loading the project.

**Comment by Zen64** [comment]
Ah, thank you, I'll try that now! And no, this is an NTSC GC copy, not Wii.
