### ISSUE TITLE
Fails to load symbol map (NoClassDefFoundError: DemangledMethod)

### ISSUE THREAD

**Issue by RenaKunisaki** [Cuyler36/Ghidra-GameCube-Loader#55]
Loading a DOL fails when trying to use a symbol map:

```
ghidra/app/util/demangler/DemangledMethod
java.lang.NoClassDefFoundError: ghidra/app/util/demangler/DemangledMethod
	at gamecubeloader.common.SymbolLoader.ApplySymbols(SymbolLoader.java:456)
	at gamecubeloader.dol.DOLProgramBuilder.load(DOLProgramBuilder.java:114)
	at gamecubeloader.dol.DOLProgramBuilder.<init>(DOLProgramBuilder.java:37)
	at gamecubeloader.GameCubeLoader.loadProgramInto(GameCubeLoader.java:169)
	at ghidra.app.util.opinion.AbstractProgramLoader.loadInto(AbstractProgramLoader.java:169)
	at gamecubeloader.GameCubeLoader.loadProgram(GameCubeLoader.java:140)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:112)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:404)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:350)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: ghidra.app.util.demangler.DemangledMethod
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 15 more

---------------------------------------------------
Build Date: 2022-Apr-21 2337 CEST
Ghidra Version: 10.1.3
Java Home: /usr/lib/jvm/java-18-openjdk
JVM Version: N/A 18.0.1.1
OS: Linux 5.15.40-1-lts amd64
Workstation: lopmon
```

**Comment by RenaKunisaki** [comment]
Nevermind ghidra is a butt and I was still loading an old version
