### ISSUE TITLE
World of Goo binary does not work

### ISSUE THREAD

**Issue by Fancy2209** [Cuyler36/Ghidra-GameCube-Loader#80]
When I try to load World of Goo's binary (00000001.app) Ghidra tells me the following
```
The loaded list must not be empty
java.lang.IllegalArgumentException: The loaded list must not be empty
	at ghidra.app.util.opinion.LoadResults.<init>(LoadResults.java:50)
	at ghidra.app.util.opinion.AbstractProgramLoader.load(AbstractProgramLoader.java:147)
	at ghidra.plugin.importer.ImporterUtilities.importSingleFile(ImporterUtilities.java:388)
	at ghidra.plugin.importer.ImporterDialog.lambda$okCallback$7(ImporterDialog.java:347)
	at ghidra.util.task.TaskBuilder$TaskBuilderTask.run(TaskBuilder.java:306)
	at ghidra.util.task.Task.monitoredRun(Task.java:134)
	at ghidra.util.task.TaskRunner.lambda$startTaskThread$0(TaskRunner.java:106)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

---------------------------------------------------
Build Date: 2023-Jun-14 1629 EDT
Ghidra Version: 10.3.1
Java Home: C:\Program Files\Eclipse Adoptium\jdk-17.0.8.101-hotspot
JVM Version: Eclipse Adoptium 17.0.8.1
OS: Windows 11 10.0 amd64

```

**Comment by Fancy2209** [comment]
I got extremely confused, the binary is actually 00000006.app

**Comment by Fancy2209** [comment]
nvm, i got confused by it opening, it's not

**Comment by MaplePsyrup** [comment]
I was running into this issue with a few WiiWare titles as well but eventually figured it out. The `00000001.app` file for many games is often compressed in a way that tools like ShowMiiWads and BrawlCrate don't seem to pick up on. Fortunately you can still decompress these files with wwcxtool from wwPacker. For example  `.\wwcxtool.exe /u 00000001.app 00000001_decomp.app` will produce a decompressed app file that Ghidra can decompile. I was personally trying to decompile Pokemon Rumble but I specifically tested this with World of Goo as well to confirm. Hope this helps.

**Comment by Fancy2209** [comment]
yep, that works, thanks!
